apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: jg367lldk-go
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-go:bc6f5e4927bc462a66ee9826f6fd1f36a7437bd7@sha256:eacb7e130d3ab9db3bf3c9e020815c7c28798b2e78a7cef9c43c6f653e465e9c
          name: container-image
